/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controlador.ControladorMedicamento;
import controlador.ControladorProfesional;
import java.awt.Color;
import java.awt.event.KeyEvent;
import VO.CentroMedico;
import VO.Cita;
import VO.Fecha;
import VO.Profesional;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import VO.Medicamento;

/**
 *
 * @author 416pc01
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private CentroMedico centro;
    private final ControladorProfesional controlador;
    private final ControladorMedicamento controladorM;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        centro = new CentroMedico();
        controlador = new ControladorProfesional();
        controladorM = new ControladorMedicamento();
        listar();
        listarMedicamentos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPOpcionConsulta = new javax.swing.JTabbedPane();
        jPRegistroMedico = new javax.swing.JPanel();
        jPDatosMedico = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jLCedula = new javax.swing.JLabel();
        jLRegistroMedico = new javax.swing.JLabel();
        jLEspecialidad = new javax.swing.JLabel();
        jLNumTel = new javax.swing.JLabel();
        jTFNombreMedico = new javax.swing.JTextField();
        jTFCedulaMedico = new javax.swing.JTextField();
        jTFRegisMedico = new javax.swing.JTextField();
        jTFNumTelMedico = new javax.swing.JTextField();
        jCBEspeciMedico = new javax.swing.JComboBox();
        jPOpcion = new javax.swing.JPanel();
        jBGuardar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        MiPrimeraTabla = new javax.swing.JTable();
        jPRegistroCita = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jLNumeroId = new javax.swing.JLabel();
        jLTipoId = new javax.swing.JLabel();
        jLEdad = new javax.swing.JLabel();
        jLGenero = new javax.swing.JLabel();
        jLTel = new javax.swing.JLabel();
        jLHora = new javax.swing.JLabel();
        jLFecha = new javax.swing.JLabel();
        jLMedico = new javax.swing.JLabel();
        jLObservacion = new javax.swing.JLabel();
        jTFPaciente = new javax.swing.JTextField();
        jTFNumId = new javax.swing.JTextField();
        jTFEdad = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jCBTipoId = new javax.swing.JComboBox();
        jCBGenero = new javax.swing.JComboBox();
        jCBHora = new javax.swing.JComboBox();
        jCBDia = new javax.swing.JComboBox();
        jCBMes = new javax.swing.JComboBox();
        jCBAño = new javax.swing.JComboBox();
        jCBMedico = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAObservacion = new javax.swing.JTextArea();
        jPOpciones = new javax.swing.JPanel();
        jBAsignarCita = new javax.swing.JButton();
        jBCancelarRegistro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLNumerosIdentificacion = new javax.swing.JList();
        jBVer = new javax.swing.JButton();
        jLNumeroIdent = new javax.swing.JLabel();
        jTFNumeroidentificacionCitas = new javax.swing.JTextField();
        jBCancelarCita = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNombreM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFCantidadM = new javax.swing.JTextField();
        jBBuscarM = new javax.swing.JButton();
        jBEliminarM = new javax.swing.JButton();
        jBModificarM = new javax.swing.JButton();
        jBRegistrarM = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        MiSegundaTabla = new javax.swing.JTable();
        jLTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTPOpcionConsulta.setForeground(new java.awt.Color(0, 153, 255));
        jTPOpcionConsulta.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTPOpcionConsulta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTPOpcionConsultaStateChanged(evt);
            }
        });

        jPRegistroMedico.setBackground(new java.awt.Color(255, 255, 255));
        jPRegistroMedico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 2));

        jPDatosMedico.setBackground(new java.awt.Color(255, 255, 255));
        jPDatosMedico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 102), 2), "Datos del profesional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jLNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 153, 255));
        jLNombre.setText("Nombre");

        jLCedula.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLCedula.setForeground(new java.awt.Color(0, 153, 255));
        jLCedula.setText("Cedula");

        jLRegistroMedico.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLRegistroMedico.setForeground(new java.awt.Color(0, 153, 255));
        jLRegistroMedico.setText("Registro Medico");

        jLEspecialidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLEspecialidad.setForeground(new java.awt.Color(0, 153, 255));
        jLEspecialidad.setText("Especialidad");

        jLNumTel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLNumTel.setForeground(new java.awt.Color(0, 153, 255));
        jLNumTel.setText("Numero Telefonico");

        jTFNombreMedico.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFNombreMedico.setForeground(new java.awt.Color(0, 153, 255));
        jTFNombreMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNombreMedicoKeyTyped(evt);
            }
        });

        jTFCedulaMedico.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFCedulaMedico.setForeground(new java.awt.Color(0, 153, 255));
        jTFCedulaMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCedulaMedicoKeyTyped(evt);
            }
        });

        jTFRegisMedico.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFRegisMedico.setForeground(new java.awt.Color(0, 153, 255));
        jTFRegisMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFRegisMedicoKeyTyped(evt);
            }
        });

        jTFNumTelMedico.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFNumTelMedico.setForeground(new java.awt.Color(0, 153, 255));
        jTFNumTelMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFNumTelMedicoKeyTyped(evt);
            }
        });

        jCBEspeciMedico.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jCBEspeciMedico.setForeground(new java.awt.Color(0, 153, 255));
        jCBEspeciMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Opcion", "Cirujia General", "Anestesiologia y Recuperacion", "Cardiologia", "Dermatologia", "Endocrinologia", "Hematologia", "Infectologia", "Medicina Materno Fetal", "Medicina Interna", "Gastroenterologia", "Neumologia" }));

        jPOpcion.setBackground(new java.awt.Color(255, 255, 255));
        jPOpcion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 2), "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jPOpcion.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jBGuardar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(0, 153, 255));
        jBGuardar.setText("REGISTRAR");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBBuscar.setForeground(new java.awt.Color(0, 153, 255));
        jBBuscar.setText("BUSCAR");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBEliminar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(0, 153, 255));
        jBEliminar.setText("ELIMINAR");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOpcionLayout = new javax.swing.GroupLayout(jPOpcion);
        jPOpcion.setLayout(jPOpcionLayout);
        jPOpcionLayout.setHorizontalGroup(
            jPOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionLayout.createSequentialGroup()
                .addGroup(jPOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOpcionLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jBGuardar)
                        .addGap(66, 66, 66)
                        .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPOpcionLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPOpcionLayout.setVerticalGroup(
            jPOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jBEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MiPrimeraTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(MiPrimeraTabla);

        javax.swing.GroupLayout jPDatosMedicoLayout = new javax.swing.GroupLayout(jPDatosMedico);
        jPDatosMedico.setLayout(jPDatosMedicoLayout);
        jPDatosMedicoLayout.setHorizontalGroup(
            jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosMedicoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosMedicoLayout.createSequentialGroup()
                        .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombre)
                            .addComponent(jLCedula)
                            .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPDatosMedicoLayout.createSequentialGroup()
                                    .addComponent(jLEspecialidad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBEspeciMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFCedulaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPDatosMedicoLayout.createSequentialGroup()
                                        .addComponent(jLRegistroMedico)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFRegisMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTFNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addComponent(jPOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPDatosMedicoLayout.createSequentialGroup()
                        .addComponent(jLNumTel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNumTelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPDatosMedicoLayout.setVerticalGroup(
            jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosMedicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosMedicoLayout.createSequentialGroup()
                        .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombre)
                            .addComponent(jTFNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCedula)
                            .addComponent(jTFCedulaMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRegistroMedico)
                            .addComponent(jTFRegisMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLEspecialidad)
                    .addComponent(jCBEspeciMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosMedicoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPDatosMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLNumTel)
                            .addComponent(jTFNumTelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPDatosMedicoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(149, 149, 149))
        );

        javax.swing.GroupLayout jPRegistroMedicoLayout = new javax.swing.GroupLayout(jPRegistroMedico);
        jPRegistroMedico.setLayout(jPRegistroMedicoLayout);
        jPRegistroMedicoLayout.setHorizontalGroup(
            jPRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDatosMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPRegistroMedicoLayout.setVerticalGroup(
            jPRegistroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroMedicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDatosMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTPOpcionConsulta.addTab("Registro Profesional", jPRegistroMedico);

        jPRegistroCita.setBackground(new java.awt.Color(255, 255, 255));
        jPRegistroCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 2));

        jLUsuario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLUsuario.setForeground(new java.awt.Color(0, 153, 255));
        jLUsuario.setText("Usuario");

        jLNumeroId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLNumeroId.setForeground(new java.awt.Color(0, 153, 255));
        jLNumeroId.setText("Numero Identificacion");

        jLTipoId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLTipoId.setForeground(new java.awt.Color(0, 153, 255));
        jLTipoId.setText("Tipo de Identificacion");

        jLEdad.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLEdad.setForeground(new java.awt.Color(0, 153, 255));
        jLEdad.setText("Edad");

        jLGenero.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLGenero.setForeground(new java.awt.Color(0, 153, 255));
        jLGenero.setText("Genero");

        jLTel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLTel.setForeground(new java.awt.Color(0, 153, 255));
        jLTel.setText("Telefono");

        jLHora.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLHora.setForeground(new java.awt.Color(0, 153, 255));
        jLHora.setText("Hora");

        jLFecha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLFecha.setForeground(new java.awt.Color(0, 153, 255));
        jLFecha.setText("Fecha");

        jLMedico.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLMedico.setForeground(new java.awt.Color(0, 153, 255));
        jLMedico.setText("Medico");

        jLObservacion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLObservacion.setForeground(new java.awt.Color(0, 153, 255));
        jLObservacion.setText("Observaciones");

        jTFPaciente.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTFPaciente.setForeground(new java.awt.Color(0, 255, 102));

        jTFNumId.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTFNumId.setForeground(new java.awt.Color(0, 255, 102));

        jTFEdad.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTFEdad.setForeground(new java.awt.Color(0, 255, 102));

        jTFTelefono.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(0, 255, 102));

        jCBTipoId.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBTipoId.setForeground(new java.awt.Color(0, 255, 102));
        jCBTipoId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Opcion", "Cedula", "Tarjeta de Identidad", "Pasaporte" }));

        jCBGenero.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBGenero.setForeground(new java.awt.Color(0, 255, 102));
        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Opcion", "Femenino", "Masculino" }));

        jCBHora.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBHora.setForeground(new java.awt.Color(0, 255, 102));
        jCBHora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Opcion", "8:00 am", "8:30 am", "9:00 am", "9:30 am", "10:00 am", "10:30 am", "11:00 am", "11:30 am", "12:00 am", "2:00 pm", "2:30 pm", "3:00 pm", "3:30 pm", "4:00 pm", "4:30 pm", "5:00 pm" }));

        jCBDia.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBDia.setForeground(new java.awt.Color(0, 255, 102));
        jCBDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCBMes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBMes.setForeground(new java.awt.Color(0, 255, 102));
        jCBMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jCBAño.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBAño.setForeground(new java.awt.Color(0, 255, 102));
        jCBAño.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año", "2015", "2016" }));

        jCBMedico.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jCBMedico.setForeground(new java.awt.Color(0, 255, 102));
        jCBMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el Medico", " " }));

        jTAObservacion.setColumns(20);
        jTAObservacion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTAObservacion.setForeground(new java.awt.Color(0, 255, 102));
        jTAObservacion.setRows(5);
        jScrollPane1.setViewportView(jTAObservacion);

        jPOpciones.setBackground(new java.awt.Color(255, 255, 255));
        jPOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 2), "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jBAsignarCita.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBAsignarCita.setForeground(new java.awt.Color(0, 153, 255));
        jBAsignarCita.setText("ASIGNAR CITA");
        jBAsignarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarCitaActionPerformed(evt);
            }
        });

        jBCancelarRegistro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jBCancelarRegistro.setForeground(new java.awt.Color(0, 153, 255));
        jBCancelarRegistro.setText("LIMPIAR");
        jBCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOpcionesLayout = new javax.swing.GroupLayout(jPOpciones);
        jPOpciones.setLayout(jPOpcionesLayout);
        jPOpcionesLayout.setHorizontalGroup(
            jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOpcionesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jBCancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBAsignarCita))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPOpcionesLayout.setVerticalGroup(
            jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAsignarCita)
                .addGap(18, 18, 18)
                .addComponent(jBCancelarRegistro)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 102), 2), "Opciones De la Cita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jLNumerosIdentificacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLNumerosIdentificacion.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLNumerosIdentificacionValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jLNumerosIdentificacion);

        jBVer.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jBVer.setForeground(new java.awt.Color(0, 153, 204));
        jBVer.setText("VER");
        jBVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerActionPerformed(evt);
            }
        });

        jLNumeroIdent.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLNumeroIdent.setForeground(new java.awt.Color(0, 153, 204));
        jLNumeroIdent.setText("Numero de Identificacion");

        jTFNumeroidentificacionCitas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTFNumeroidentificacionCitas.setForeground(new java.awt.Color(0, 153, 204));

        jBCancelarCita.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jBCancelarCita.setForeground(new java.awt.Color(0, 153, 204));
        jBCancelarCita.setText("CANCELAR CITA");
        jBCancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLNumeroIdent)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNumeroidentificacionCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBVer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumeroIdent)
                    .addComponent(jTFNumeroidentificacionCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVer)
                    .addComponent(jBCancelarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPRegistroCitaLayout = new javax.swing.GroupLayout(jPRegistroCita);
        jPRegistroCita.setLayout(jPRegistroCitaLayout);
        jPRegistroCitaLayout.setHorizontalGroup(
            jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroCitaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMedico)
                    .addComponent(jLFecha)
                    .addComponent(jLHora)
                    .addComponent(jLGenero)
                    .addComponent(jLTipoId)
                    .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLNumeroId, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroCitaLayout.createSequentialGroup()
                            .addComponent(jLUsuario)
                            .addGap(259, 259, 259)))
                    .addComponent(jLEdad)
                    .addComponent(jLTel)
                    .addComponent(jLObservacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPRegistroCitaLayout.createSequentialGroup()
                            .addComponent(jCBDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBMes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jCBAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTFTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFEdad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFNumId, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jCBMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRegistroCitaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(jPRegistroCitaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPRegistroCitaLayout.setVerticalGroup(
            jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRegistroCitaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jTFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRegistroCitaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNumeroId)
                            .addComponent(jTFNumId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTipoId)
                            .addComponent(jCBTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEdad)
                            .addComponent(jTFEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRegistroCitaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRegistroCitaLayout.createSequentialGroup()
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLGenero)
                            .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTel)
                            .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLHora))
                        .addGap(38, 38, 38)
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLFecha)
                            .addComponent(jCBDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLMedico)
                            .addComponent(jCBMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPRegistroCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLObservacion)))
                    .addGroup(jPRegistroCitaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPOpcionConsulta.addTab("Registro de Citas", jPRegistroCita);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 4));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Nombre ");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("MEDICAMENTOS");

        jTFNombreM.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad");

        jTFCantidadM.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jBBuscarM.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBBuscarM.setText("Buscar ");
        jBBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarMActionPerformed(evt);
            }
        });

        jBEliminarM.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBEliminarM.setText("Eliminar");
        jBEliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarMActionPerformed(evt);
            }
        });

        jBModificarM.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBModificarM.setText("Modificar");
        jBModificarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarMActionPerformed(evt);
            }
        });

        jBRegistrarM.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBRegistrarM.setText("Registrar");
        jBRegistrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarMActionPerformed(evt);
            }
        });

        MiSegundaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(MiSegundaTabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(79, 79, 79)
                        .addComponent(jTFCantidadM, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBRegistrarM)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBBuscarM)
                                            .addComponent(jBModificarM))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jBEliminarM))))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFCantidadM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBRegistrarM)
                            .addComponent(jBBuscarM))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBEliminarM)
                            .addComponent(jBModificarM)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTPOpcionConsulta.addTab("Farmacia", jPanel2);

        jLTitulo.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 153, 255));
        jLTitulo.setText("CENTRO MEDICO ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jTPOpcionConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTPOpcionConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPOpcionConsultaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTPOpcionConsultaStateChanged
        // TODO add your handling code here:
        if (jTPOpcionConsulta.getSelectedIndex() == 1) {
            refrescarMedicos();
        }
    }//GEN-LAST:event_jTPOpcionConsultaStateChanged

    private void jBVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerActionPerformed

        String identificacion = jTFNumeroidentificacionCitas.getText();
        ArrayList<String> Fechas = centro.obtenerFechaCitaPaciente(identificacion);
        jLNumerosIdentificacion.setListData(Fechas.toArray());
        jLNumerosIdentificacion.setSelectedIndex(0);

    }//GEN-LAST:event_jBVerActionPerformed

    private void jLNumerosIdentificacionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLNumerosIdentificacionValueChanged
        // TODO add your handling code here:

        if (jLNumerosIdentificacion.getSelectedValue() != null) {

            String ident = (String) jLNumerosIdentificacion.getSelectedValue();

            Cita c = centro.buscarCitaPorIdenti(ident);

        } else {
            JOptionPane.showMessageDialog(null, "No hay...");
        }
    }//GEN-LAST:event_jLNumerosIdentificacionValueChanged

    private void jBCancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarCitaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBCancelarCitaActionPerformed

    private void jBCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarRegistroActionPerformed
        // TODO add your handling code here:ç
        limpiarCamposCancelar();
    }//GEN-LAST:event_jBCancelarRegistroActionPerformed

    private void jBAsignarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsignarCitaActionPerformed
        // TODO add your handling code here:
        String usu = jTFPaciente.getText();
        String id = jTFNumId.getText();
        String tipoId = (String) jCBTipoId.getSelectedItem();
        short edad = Short.parseShort(jTFEdad.getText());
        String gen = (String) jCBGenero.getSelectedItem();
        String numTel = jTFNumTelMedico.getText();
        String hora = (String) jCBHora.getSelectedItem();
        String obser = jTAObservacion.getText();
        int dia = jCBDia.getSelectedIndex();
        int mes = jCBMes.getSelectedIndex();
        int anio = Integer.parseInt((String) jCBAño.getSelectedItem());

        Profesional m = centro.buscarMedicoNombre((String) jCBMedico.getSelectedItem());

        Fecha f = new Fecha(dia, mes, anio);

        Cita c = new Cita(usu, id, tipoId, edad, gen, numTel, hora, obser, f, m);
        String asignacion = centro.asignarCita(c);
        JOptionPane.showMessageDialog(null, asignacion);
    }//GEN-LAST:event_jBAsignarCitaActionPerformed

    private void jTFNumTelMedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNumTelMedicoKeyTyped
        noRecibirLetras(evt);
    }//GEN-LAST:event_jTFNumTelMedicoKeyTyped

    private void jTFRegisMedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFRegisMedicoKeyTyped
        noRecibirNumeros(evt);
    }//GEN-LAST:event_jTFRegisMedicoKeyTyped

    private void jTFCedulaMedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCedulaMedicoKeyTyped
        noRecibirLetras(evt);
    }//GEN-LAST:event_jTFCedulaMedicoKeyTyped

    private void jTFNombreMedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreMedicoKeyTyped
        noRecibirNumeros(evt);
    }//GEN-LAST:event_jTFNombreMedicoKeyTyped

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed

        String medico = JOptionPane.showInputDialog(null, "Ingrese la cedula del profesional:");

        Profesional ced = controlador.buscarProfesional(medico);
        if (ced != null) {

            JOptionPane.showMessageDialog(null, "Se ha encontrado el profesional.");
            jTFNombreMedico.setText(ced.getNombre());
            jTFCedulaMedico.setText(ced.getCedula());
            jTFRegisMedico.setText(ced.getRm());
            jCBEspeciMedico.setSelectedItem(ced.getEspecializacion());
            jTFNumTelMedico.setText(ced.getNumCel());

        } else {
            JOptionPane.showMessageDialog(null, "No se ha encontrado el profesional ingresado");
            LimpiarCampos();
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        String nom = jTFNombreMedico.getText();
        String ced = jTFCedulaMedico.getText();
        String numCel = jTFNumTelMedico.getText();
        String rm = jTFRegisMedico.getText();
        String especializacion = (String) jCBEspeciMedico.getSelectedItem();
        if (nom.isEmpty() || ced.isEmpty() || numCel.isEmpty() || rm.isEmpty() || especializacion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");

        } else {
            Profesional p = new Profesional(nom, ced, numCel, rm, especializacion);
            boolean ban = controlador.RegistrarProfesional(p);
            if (!ban) {
                JOptionPane.showMessageDialog(null, "Se ha registrado correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "El profesional no se registro");
            }

            LimpiarCampos();

            listar();
        }
    }//GEN-LAST:event_jBGuardarActionPerformed


    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:

        String ced = jTFCedulaMedico.getText();
        boolean res = controlador.eliminarProfesional(ced);
        listar();
        LimpiarCampos();

    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarMActionPerformed
        // TODO add your handling code here:
        String medico = JOptionPane.showInputDialog(null, "Ingrese el nombre del medicamento:");

        Medicamento me = controladorM.buscarMedicamento(medico);
        if (me != null) {

            JOptionPane.showMessageDialog(null, "Se ha encontrado el medicamento.");
            listarMedicamentos();

        } else {
            JOptionPane.showMessageDialog(null, "No se ha encontrado el medicamento ingresado");
            LimpiarCampos();
        }
    }//GEN-LAST:event_jBBuscarMActionPerformed

    private void jBModificarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarMActionPerformed
        // TODO add your handling code here:
        String nom = jTFNombreM.getText();
        if (nom != null) {
            Medicamento m = controladorM.buscarMedicamento(jTFNombreM.getText());
            
            m.setCantidad(Integer.parseInt(jTFCantidadM.getText()));

            boolean ban = controladorM.modificarMedicamento(m);
            JOptionPane.showMessageDialog(null, ban);
            JOptionPane.showMessageDialog(null,"Se modifico");
            LimpiarCampos();
            listar();

        } else {
            JOptionPane.showMessageDialog(null, "No hay usuarios registrados.");

        }
    }//GEN-LAST:event_jBModificarMActionPerformed

    private void jBRegistrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarMActionPerformed
        // TODO add your handling code here:

        String nom = jTFNombreM.getText();
        int cantidad = Integer.parseInt(jTFCantidadM.getText());

        Medicamento m = new Medicamento(nom, cantidad);

        boolean ban = controladorM.RegistrarMedicamento(m);
        if (!ban) {
            JOptionPane.showMessageDialog(null, "Se ha registrado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "El Medicamento no se registro");
        }

        LimpiarCampos();

        listarMedicamentos();

    }//GEN-LAST:event_jBRegistrarMActionPerformed

    private void jBEliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarMActionPerformed
        // TODO add your handling code here:

        String nom = jTFNombreM.getText();
        boolean res = controladorM.eliminarMedicamento(nom);
        listarMedicamentos();
        LimpiarCampos();
    }//GEN-LAST:event_jBEliminarMActionPerformed

    private void listar() {

        Vector columnas = new Vector();
        columnas.add("Nombre");
        columnas.add("Cedula");
        columnas.add("Numero Celular");
        columnas.add("Registro Medico");
        columnas.add("Especialidad");
        DefaultTableModel dtm = new DefaultTableModel(null, columnas);
        ArrayList<Profesional> usuarios = controlador.obtenerProfesionals();
        for (Profesional usu : usuarios) {
            Vector datos = new Vector();
            datos.add(usu.getNombre());
            datos.add(usu.getCedula());
            datos.add(usu.getNumCel());
            datos.add(usu.getRm());
            datos.add(usu.getEspecializacion());
            dtm.addRow(datos);
        }
        MiPrimeraTabla.setModel(dtm);
    }

    private void listarMedicamentos() {

        Vector columnas = new Vector();
        columnas.add("Nombre");
        columnas.add("Cantidad");

        DefaultTableModel dtm = new DefaultTableModel(null, columnas);
        ArrayList<Medicamento> medicamento = controladorM.obtenerMedicamento();
        for (Medicamento me : medicamento) {
            Vector datos = new Vector();
            datos.add(me.getNombre());
            datos.add(me.getCantidad());

            dtm.addRow(datos);
        }
        MiSegundaTabla.setModel(dtm);
    }

    public void noRecibirLetras(KeyEvent e) {
        if (!Character.isDigit((char) e.getKeyChar())) {
            // esta instruccion borra el caracter digitado
            //cuando no es un numero
            e.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }

    public void noRecibirNumeros(KeyEvent e) {
        /*
         * hay que evaluar si el caracter dIGitado no es una letra
         * es decir si es una letra o un caracter especial
         */

        if (!Character.isLetter((char) e.getKeyChar())) {
            // esta instruccion borra el caracter digitado
            //cuando no es una letra
            e.setKeyChar((char) KeyEvent.VK_CLEAR);
        }

    }

    private void limpiarCamposCancelar() {
        jTFPaciente.setText(null);
        jTFNumId.setText(null);
        jCBTipoId.setSelectedItem(null);
        jTFEdad.setText(null);
        jCBGenero.setSelectedItem(null);
        jTFTelefono.setText(null);
        jCBHora.setSelectedItem(null);
        jCBDia.setSelectedItem(null);
        jCBMes.setSelectedItem(null);
        jCBAño.setSelectedItem(null);
        jCBMedico.setSelectedItem(null);
        jTAObservacion.setText(null);

    }

    public void refrescarMedicos() {
        ArrayList<String> nombres = centro.obtenerNombresMedicos();
        jCBMedico.removeAllItems();
        jCBMedico.addItem("Seleccione el medico");
        for (int i = 0; i < nombres.size(); i++) {
            jCBMedico.addItem(nombres.get(i));

        }
        jCBMedico.removeAllItems();
        jCBMedico.addItem("Seleccione el medico");
        for (int i = 0; i < nombres.size(); i++) {
            jCBMedico.addItem(nombres.get(i));

        }

    }

    public void LimpiarCampos() {
        jTFNombreMedico.setText(null);
        jTFCedulaMedico.setText(null);
        jTFRegisMedico.setText(null);
        jCBEspeciMedico.setSelectedItem(null);
        jTFTelefono.setText(null);
        jTFNumTelMedico.setText(null);
        jTFNombreM.setText(null);
        jTFCantidadM.setText(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MiPrimeraTabla;
    private javax.swing.JTable MiSegundaTabla;
    private javax.swing.JButton jBAsignarCita;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBBuscarM;
    private javax.swing.JButton jBCancelarCita;
    private javax.swing.JButton jBCancelarRegistro;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBEliminarM;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificarM;
    private javax.swing.JButton jBRegistrarM;
    private javax.swing.JButton jBVer;
    private javax.swing.JComboBox jCBAño;
    private javax.swing.JComboBox jCBDia;
    private javax.swing.JComboBox jCBEspeciMedico;
    private javax.swing.JComboBox jCBGenero;
    private javax.swing.JComboBox jCBHora;
    private javax.swing.JComboBox jCBMedico;
    private javax.swing.JComboBox jCBMes;
    private javax.swing.JComboBox jCBTipoId;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLEdad;
    private javax.swing.JLabel jLEspecialidad;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLHora;
    private javax.swing.JLabel jLMedico;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNumTel;
    private javax.swing.JLabel jLNumeroId;
    private javax.swing.JLabel jLNumeroIdent;
    private javax.swing.JList jLNumerosIdentificacion;
    private javax.swing.JLabel jLObservacion;
    private javax.swing.JLabel jLRegistroMedico;
    private javax.swing.JLabel jLTel;
    private javax.swing.JLabel jLTipoId;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPDatosMedico;
    private javax.swing.JPanel jPOpcion;
    private javax.swing.JPanel jPOpciones;
    private javax.swing.JPanel jPRegistroCita;
    private javax.swing.JPanel jPRegistroMedico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTAObservacion;
    private javax.swing.JTextField jTFCantidadM;
    private javax.swing.JTextField jTFCedulaMedico;
    private javax.swing.JTextField jTFEdad;
    private javax.swing.JTextField jTFNombreM;
    private javax.swing.JTextField jTFNombreMedico;
    private javax.swing.JTextField jTFNumId;
    private javax.swing.JTextField jTFNumTelMedico;
    private javax.swing.JTextField jTFNumeroidentificacionCitas;
    private javax.swing.JTextField jTFPaciente;
    private javax.swing.JTextField jTFRegisMedico;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTabbedPane jTPOpcionConsulta;
    // End of variables declaration//GEN-END:variables
}
